workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Build the app with Xcode
        script: |
          xcodebuild -workspace DrayFireEditor.xcworkspace -scheme DrayFireEditor -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/DrayFireEditor.xcarchive archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/DrayFireEditor.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
