workflows:
  ios-workflow:
    name: iOS Workflow
    environment:
      xcode: latest
    scripts:
      - name: Build the app with Swift Package Manager
        script: |
          swift build -c release
      - name: Export IPA
        script: |
          xcodebuild -create-xcframework -framework ./build/release/DrayFireEditor.framework -output $CM_BUILD_DIR/DrayFireEditor.xcframework
    artifacts:
      - $CM_BUILD_DIR/*.xcframework

